language: java
jdk:
  - openjdk11
dist: trusty
before_install:
  - export TZ=GMT-3
  - chmod +x gradlew
jobs:
  include:
    - stage: test
    - stage: build docker image
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/accounting-service:$TRAVIS_BUILD_ID .
        - docker tag $DOCKER_USERNAME/accounting-service:$TRAVIS_BUILD_ID $DOCKER_USERNAME/accounting-service:latest
        - docker images
        - docker push $DOCKER_USERNAME/accounting-service:$TRAVIS_BUILD_ID
        - docker push $DOCKER_USERNAME/accounting-service:latest
    - stage: deploy
      if: branch = master
      script: skip
      deploy:
        provider: heroku
        api_key: $SECURE_KEY
        app: $APP
