language: java
jdk:
  - openjdk11
dist: trusty
before_install:
  - export TZ=GMT-3
  - chmod +x gradlew

deploy:
  provider: heroku
  api_key:
    - secure: $SECURE_KEY
  app: $APP
#jobs:
#  include:
#    - stage: unit tests
#    - stage: deploy
#      if: branch = master

#deploy:
#  provider: heroku:git
#  app: accounting-service
#  api_key:
#    secure: <API_KEY_ENCRYPTED>
#  edge: true
#  on:
#    branch: master

