server:
  port : 8080
spring:
  h2.console.enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update